blueprint:
  name: Presence-activated Light
  description: Turn on a light when presence is detected.
  domain: automation
  source_url: https://github.com/lekimtek/blueprints/presence_light.yaml
  input:
    Presence_entity:
      name: Presence Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: presence
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_Presence_wait:
      name: Wait time
      description: Time to leave the light on after last presence is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

# If presence is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input Presence_entity
  from: "off"
  to: "on"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
  - alias: "Wait until there is no presence from device"
    wait_for_trigger:
      platform: state
      entity_id: !input Presence_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_Presence_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
